name: AutoJail
version: ${project.version}
main: me.luanfy.autojail.AutoJail
api-version: 1.13
description: Allows you to send a user to jail upon clicking them
commands:
  jailwand:
    usage: /<command>
    description: Jail someone!
  revive:
    usage: /<command>
    description: Revives a random jailed person!
